import type { Operator, OperatorContext, OperatorResult } from "./base"
import type { PlannedTask } from "../planner/task-graph"
import { skillRegistry } from "../skills/registry"
import type { ArtifactRecord } from "../governance/artifact"

interface ArtifactInventory {
  totalCount: number
  byType: Record<string, number>
  byOperator: Record<string, number>
  artifacts: {
    id: string
    type: string
    name: string
    path: string
    producedBy: string
    timestamp: string
  }[]
}

export class ArtifactOperator implements Operator {
  type = "artifact"

  async execute(task: PlannedTask, ctx: OperatorContext): Promise<OperatorResult> {
    // 1. Check for artifact-audit skill (for future use)
    const skillId = "artifact-audit"
    const skill = skillRegistry.get(skillId)

    // 2. Gather artifacts from contextPack
    const contextPack = ctx.contextPack
    const artifacts = contextPack?.artifacts || []

    // 3. Classify and index artifacts
    const byType: Record<string, number> = {}
    const byOperator: Record<string, number> = {}

    for (const artifact of artifacts) {
      byType[artifact.type] = (byType[artifact.type] || 0) + 1
      byOperator[artifact.producedBy] = (byOperator[artifact.producedBy] || 0) + 1
    }

    // 4. Create inventory
    const inventory: ArtifactInventory = {
      totalCount: artifacts.length,
      byType,
      byOperator,
      artifacts: artifacts.map((a) => ({
        id: a.id,
        type: a.type,
        name: a.name,
        path: a.path,
        producedBy: a.producedBy,
        timestamp: a.timestamp,
      })),
    }

    // 5. Produce artifact inventory file
    const artifactRecord: ArtifactRecord = {
      id: `artifact-inventory-${Date.now()}`,
      sessionId: ctx.sessionId,
      taskId: task.id,
      producingOperator: this.type,
      type: "artifact_inventory",
      description: "Artifact inventory generated by ArtifactOperator",
      path: `artifact-inventory.json`,
      timestamp: new Date().toISOString(),
    }

    return {
      success: true,
      output: inventory,
      artifacts: [artifactRecord],
    }
  }
}
