import type { Operator, OperatorContext, OperatorResult } from "./base"
import type { PlannedTask } from "../planner/task-graph"
import { skillRegistry } from "../skills/registry"
import type { ArtifactRecord } from "../governance/artifact"

interface ReleaseReadiness {
  status: "ready" | "blocked" | "needs-work"
  blockers: string[]
  warnings: string[]
  missingEvidence: string[]
}

export class ReleaseOperator implements Operator {
  type = "release"

  async execute(task: PlannedTask, ctx: OperatorContext): Promise<OperatorResult> {
    // 1. Check for release-readiness skill (for future use)
    const skillId = "release-readiness"
    const skill = skillRegistry.get(skillId)

    // 2. Gather context from contextPack
    const contextPack = ctx.contextPack

    // 3. Gather evidence from previous steps
    const trustState = contextPack?.trustState
    const artifacts = contextPack?.artifacts || []
    const risks = contextPack?.risks || []
    const findings = contextPack?.validatedFindings || []

    // 4. Determine readiness
    const blockers: string[] = []
    const warnings: string[] = []
    const missingEvidence: string[] = []

    // Check trust score
    const trustScore = trustState?.score || 0
    if (trustScore < 0.5) {
      blockers.push(`Trust score too low: ${trustScore}`)
    }

    // Check for verification report
    const hasVerification = artifacts.some((a) => a.type === "verification_report")
    if (!hasVerification) {
      missingEvidence.push("Verification report missing - run verify first")
    }

    // Check for artifact inventory
    const hasInventory = artifacts.some((a) => a.type === "artifact_inventory")
    if (!hasInventory) {
      missingEvidence.push("Artifact inventory missing - run artifact indexing first")
    }

    // Check for critical risks
    const criticalRisks = risks.filter((r) => r.impact === "high" && r.status === "identified")
    if (criticalRisks.length > 0) {
      blockers.push(`${criticalRisks.length} critical risks identified`)
    }

    // Check for critical findings
    const criticalFindings = findings.filter((f) => f.severity === "critical")
    if (criticalFindings.length > 0) {
      blockers.push(`${criticalFindings.length} critical findings`)
    }

    // Determine overall status
    let status: "ready" | "blocked" | "needs-work" = "ready"
    if (blockers.length > 0) {
      status = "blocked"
    } else if (warnings.length > 0 || missingEvidence.length > 0) {
      status = "needs-work"
    }

    // 5. Create release readiness report
    const report: ReleaseReadiness = {
      status,
      blockers,
      warnings,
      missingEvidence,
    }

    // 6. Produce artifact
    const artifact: ArtifactRecord = {
      id: `release-readiness-${Date.now()}`,
      sessionId: ctx.sessionId,
      taskId: task.id,
      producingOperator: this.type,
      type: "release_report",
      description: "Release readiness report generated by ReleaseOperator",
      path: `release-readiness.json`,
      timestamp: new Date().toISOString(),
    }

    return {
      success: true,
      output: report,
      artifacts: [artifact],
    }
  }
}
