import type { Operator, OperatorContext, OperatorResult } from "./base"
import type { PlannedTask } from "../planner/task-graph"
import { skillRegistry } from "../skills/registry"
import type { ArtifactRecord } from "../governance/artifact"

interface VerificationCheck {
  id: string
  name: string
  passed: boolean
  details: string
}

interface VerificationReport {
  checks: VerificationCheck[]
  blockers: string[]
  warnings: string[]
  evidence: string[]
  trustScore: number
}

export class VerifyOperator implements Operator {
  type = "verify"

  async execute(task: PlannedTask, ctx: OperatorContext): Promise<OperatorResult> {
    // 1. Check for trust-verify skill (for future use)
    const skillId = "trust-verify"
    const skill = skillRegistry.get(skillId)

    // 2. Gather context from contextPack if available
    const contextPack = ctx.contextPack

    // 3. Run verification checks
    const checks = this.runVerificationChecks(contextPack)

    // 4. Identify blockers and warnings
    const blockers = checks.filter((c) => !c.passed && c.details.includes("critical")).map((c) => c.name)
    const warnings = checks.filter((c) => !c.passed && !c.details.includes("critical")).map((c) => c.name)

    // 5. Determine trust score based on checks
    const passedCount = checks.filter((c) => c.passed).length
    const trustScore = passedCount / checks.length

    // 6. Gather evidence (artifacts from previous steps)
    const evidence = contextPack?.artifacts?.map((a) => a.path) || []

    // 7. Create verification report
    const report: VerificationReport = {
      checks,
      blockers,
      warnings,
      evidence,
      trustScore,
    }

    // 8. Produce artifact
    const artifact: ArtifactRecord = {
      id: `verify-report-${Date.now()}`,
      sessionId: ctx.sessionId,
      taskId: task.id,
      producingOperator: this.type,
      type: "verification_report",
      description: "Verification report generated by VerifyOperator",
      path: `verification-report.json`,
      timestamp: new Date().toISOString(),
    }

    // 9. Emit trust delta (if trust is low)
    const trustDelta =
      trustScore < 0.5
        ? {
            taskId: task.id,
            change: -0.1,
            reason: "Verification failed: critical blockers found",
            timestamp: new Date().toISOString(),
          }
        : { taskId: task.id, change: 0.05, reason: "Verification passed", timestamp: new Date().toISOString() }

    return {
      success: true,
      output: report,
      artifacts: [artifact],
      trustDelta,
      findings: blockers.map((b) => ({
        id: `finding-${b}`,
        type: "security_risk" as const,
        severity: "critical" as const,
        title: `Blocker: ${b}`,
        description: `Verification check failed for ${b}`,
        evidence: [],
        confirmed: true,
        timestamp: new Date().toISOString(),
      })),
      risks: warnings.map((w) => ({
        id: `risk-${w}`,
        description: `Warning: ${w}`,
        likelihood: "medium" as const,
        impact: "medium" as const,
        status: "identified" as const,
        timestamp: new Date().toISOString(),
      })),
    }
  }

  private runVerificationChecks(contextPack: any): VerificationCheck[] {
    const checks: VerificationCheck[] = []

    // Check 1: Are there artifacts from explore?
    const hasExploreArtifacts = contextPack?.artifacts?.some((a: any) => a.type === "explore_report")
    checks.push({
      id: "check-explore-artifacts",
      name: "Explore Artifacts Present",
      passed: !!hasExploreArtifacts,
      details: hasExploreArtifacts ? "Explore artifacts found" : "No explore artifacts found - run explore first",
    })

    // Check 2: Is the trust score above threshold?
    const trustScore = contextPack?.trustState?.score || 0
    checks.push({
      id: "check-trust-score",
      name: "Trust Score Threshold",
      passed: trustScore >= 0.3,
      details: `Trust score is ${trustScore}`,
    })

    // Check 3: Are there any open critical questions?
    const criticalQuestions = contextPack?.openQuestions?.filter(
      (q: any) => q.priority === "high" && q.status === "unanswered",
    )
    checks.push({
      id: "check-open-questions",
      name: "No Blocking Questions",
      passed: !criticalQuestions || criticalQuestions.length === 0,
      details: criticalQuestions?.length
        ? `${criticalQuestions.length} high-priority questions unanswered`
        : "No blocking questions",
    })

    return checks
  }
}
