export const DAX_SETTING = {
  explain_mode: "explain_mode",
  policy_profile: "policy_profile",
  eli12_summary_visibility: "eli12_summary_visibility",
  session_pane_visibility: "session_pane_visibility",
  session_pane_mode: "session_pane_mode",
  session_pane_follow_mode: "session_pane_follow_mode",
  session_workflow_mode: "session_workflow_mode",
  session_pm_tab: "session_pm_tab",
  session_stream_slow: "session_stream_slow",
  toast_position: "toast_position",
  toast_style: "toast_style",
  session_preferred_name_prefix: "session_preferred_name_prefix",
  preferred_name_default: "preferred_name_default",
} as const
